# Generated by Django 2.2.5 on 2019-11-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='edad',
            new_name='age',
        ),
    ]
