# Generated by Django 2.2.5 on 2019-11-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191129_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_id',
            new_name='user',
        ),
       
    ]
