# Generated by Django 2.2.5 on 2019-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191129_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='empresa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
