# Generated by Django 2.2.5 on 2019-12-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191201_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='user',
            new_name='user_id',
        ),
    ]
