# Generated by Django 2.2.5 on 2019-12-02 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191202_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Evento'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
