# Generated by Django 2.2.5 on 2019-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191202_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
